name: Mirror Repositories

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { src: 'https://gitlab.com/example/repo.git', dest: 'exampleuser/repo1-mirror' }
          - { src: 'https://github.com/example/repo1.git', dest: 'exampleuser/repo2-mirror' }
          - { src: 'https://gitlab.com/example/repo2.git', dest: 'exampleuser/repo3-mirror' }
          # Add more repositories as needed

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Source Remote
        run: |
          git remote add source ${{ matrix.repo.src }}
          git fetch source --tags

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Set the destination repository URL
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ matrix.repo.dest }}.git
          
          # Push all branches except HEAD
          for branch in $(git branch -r | grep 'source/' | grep -v 'HEAD' | sed 's/source\///'); do
            git push origin +refs/remotes/source/$branch:refs/heads/$branch --force;
          done

          # Push all tags
          git push origin --tags
