name: Mirror Repositories

on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Fetch repository mapping from CDN
        id: fetch_mapping
        run: |
          echo "Fetching repo mapping..."
          curl --silent "${{ secrets.CDN_MAPPING_URL }}" -o mapping.json
          cat mapping.json

      - name: Set matrix output
        id: set_matrix
        run: |
          MATRIX=$(cat mapping.json)
          echo "Matrix JSON: ${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
  
  mirror:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Source Remote
        run: |
          git remote add source "${{ matrix.repo.src }}"
          git fetch source --tags

      - name: Push to Destination Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${{ matrix.repo.dest }}.git
          
          # Push all branches except HEAD
          for branch in $(git branch -r | grep 'source/' | grep -v 'HEAD' | sed 's|source/||'); do
            git push origin +refs/remotes/source/$branch:refs/heads/$branch --force;
          done

          # Push all tags with force (to overwrite tags that already exist)
          git push origin --tags --force
