name: Mirror from GitLab

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.com/restcountries/restcountries.git
          git fetch gitlab

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/countrieslive/restcountries-mirror.git
          git push origin +refs/remotes/gitlab/*:refs/heads/* --force
